# Generated by Django 3.2.8 on 2021-10-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_networks', '0002_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
